# Generated by Django 4.0 on 2021-12-25 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('secondadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davlat_kodi', models.IntegerField(verbose_name='Davlat kodi')),
                ('davlat_nomi', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='country',
        ),
    ]
