# Generated by Django 4.0 on 2021-12-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('secondadmin', '0005_alter_viloyat_viloyat_kodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman_davlati', models.CharField(max_length=100, verbose_name='Tuman joylashgan davlat')),
                ('tuman_viloyati', models.CharField(max_length=100, verbose_name='Tuman joylashgan viloyat')),
                ('tuman_kodi', models.IntegerField(verbose_name='Viloyat kodi')),
                ('tuman_nomi', models.CharField(max_length=100, verbose_name='Viloyat nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Tumanlar',
            },
        ),
    ]
