# Generated by Django 4.0 on 2021-12-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondadmin', '0008_alter_iftum_options_iftum_owner_alter_iftum_nomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iftum',
            name='nomi',
            field=models.TextField(unique=True, verbose_name='IFTUM nomi'),
        ),
    ]
