# Generated by Django 4.0 on 2021-12-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondadmin', '0004_alter_davlatlar_options_viloyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viloyat',
            name='viloyat_kodi',
            field=models.IntegerField(verbose_name='Viloyat kodi'),
        ),
    ]
