# Generated by Django 4.0 on 2021-12-17 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='val_buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bino_nomi', models.TextField()),
                ('bino_qurilgan_vaqt', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
