# Generated by Django 4.0 on 2021-12-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0002_val_buildings_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='val_buildings',
            name='bino_qurilgan_vaqt',
        ),
    ]
