# Generated by Django 4.0 on 2021-12-17 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ges', '0003_remove_val_buildings_bino_qurilgan_vaqt'),
    ]

    operations = [
        migrations.CreateModel(
            name='v_buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bino_nomi', models.CharField(max_length=266)),
                ('oxirgi_audit', models.DateField(default=django.utils.timezone.now)),
                ('umumiy_maydoni', models.FloatField()),
                ('isitish_hajmi', models.FloatField()),
                ('isitish_maydoni', models.FloatField()),
                ('bino_turi', models.FloatField()),
                ('etajlar_soni', models.FloatField()),
                ('xonalar_soni', models.FloatField()),
                ('sovutiladigan_maydon', models.FloatField()),
                ('foydali_maydon', models.FloatField()),
                ('koridor', models.FloatField()),
                ('xodimlar_soni', models.FloatField()),
                ('ish_soatlari', models.FloatField()),
                ('yillik_energiya_sarfi', models.FloatField()),
                ('yillik_gaz_sarfi', models.FloatField()),
                ('yillik_issiqlik_sarfi', models.FloatField()),
                ('yillik_komir_sarfi', models.FloatField()),
                ('yillik_neft_mahsulotlari_sarfi', models.FloatField()),
                ('isitish_turi', models.CharField(max_length=266)),
                ('jihozlanganligi', models.CharField(max_length=266)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='val_buildings',
        ),
    ]
