# Generated by Django 4.0 on 2021-12-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0005_rename_yillik_energiya_sarfi_v_buildings_yillik_bug_sarfi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='v_buildings',
            name='isitish_turi',
        ),
    ]
