# Generated by Django 4.0 on 2021-12-17 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0008_v_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v_parameters',
            name='sana',
            field=models.DateField(default=datetime.date(2021, 12, 18)),
        ),
    ]
