# Generated by Django 4.0 on 2021-12-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='bodytext',
            field=models.TextField(verbose_name='Yozuv'),
        ),
        migrations.AlterField(
            model_name='page',
            name='permalink',
            field=models.CharField(max_length=12, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(verbose_name='Oxirgi yangilanish'),
        ),
    ]
